version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - ./Backend/.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network
    environment:
      - REACT_APP_API_URL=http://backend:${SERVER_PORT:-8080}

networks:
  todo-network:
    driver: bridge